language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "10"
  apt:
    packages:
      - oracle-java8-installer
      - postgresql-10
      - postgresql-client-10
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install language-pack-de
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 10
before_script:
  - psql -c "CREATE USER kandidatentest WITH PASSWORD 'kandidatentestpwd' LOGIN SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;" -U postgres
  - psql -c 'GRANT pg_signal_backend, postgres TO kandidatentest WITH ADMIN OPTION;' -U postgres
  - psql -c "CREATE DATABASE kandidatentest WITH OWNER = kandidatentest TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'de_DE.UTF-8' LC_CTYPE = 'de_DE.UTF-8' CONNECTION LIMIT = -1;" -U postgres
  - psql -c '\l' -U postgres
  - psql -c '\dg' -U postgres
  - psql -c '\dn' -U postgres
  - psql -c 'select * from version();' -U postgres
  - psql -c 'select * from version();' -U kandidatentest
sudo: false
script:  ./mvnw clean install jbake:generate site site:deploy -Ptravis -Dtest=AlphaTopLevelSuiteIT  -B -V



