#!/usr/bin/env bash

export DEFCON1_LOGIN_USERNAME=nbc
export DEFCON1_LOGIN_PASSWORD=natural-born-coder

# TODO
export DEFCON1_GOOGLE_APS_API_KEY=****

# TODO
export DEFCON1_GOOGLE_ANALYTICS_ID=****

# TODO
export DEFCON1_GOOGLE_WEBMASTER_TOOLS_ID=***

# TODO
export DEFCON1_MICROSOFT_WEBMASTER_TOOLS_ID=****

# TODO
export DEFCON1_FACEBOOK_APP_ID=******

# TODO
export DEFCON1_TWITTER_CARD_SITE=port80guru

# TODO
export DEFCON1_TWITTER_CARD_CREATOR=port80guru

export DEFCON1_PROFILE_DEFAULT='-Pdefault'
export DEFCON1_PROFILE_DEV_embedded='-Pdevembedded'
export DEFCON1_PROFILE_INT_embedded='-Pintembedded'
export DEFCON1_PROFILE_TEST_embedded='-Ptestembedded'
export DEFCON1_PROFILE_PROD_embedded='-Pprodembedded'
export DEFCON1_PROFILE_TRAVIS_embedded='-Ptravisembedded'
export DEFCON1_PROFILE_DEV='-Pdev'
export DEFCON1_PROFILE_INT='-Pint'
export DEFCON1_PROFILE_TEST='-Ptest'
export DEFCON1_PROFILE_PROD='-Pprod'
export DEFCON1_PROFILE_TRAVIS='-Ptravis'

export DEFCON1_PROFILE_RUN=$DEFCON1_PROFILE_DEFAULT
export DEFCON1_PROFILE_RELEASE=$DEFCON1_PROFILE_TEST_embedded
export DEFCON1_PROFILE_BUILD_JAR=$DEFCON1_PROFILE_DEFAULT

# TODO
export DEFCON1_PROFILE_RUN_JAR_LIKE_HEROKU=''

export MAVEN_OPTS="-Xmx512m"
export PORT=8080
export JAVA_OPTS='-Xmx350m -Xss512k'

