spring:
  dao:
    exceptiontranslation:
      enabled: true
  data:
    neo4j:
      URI: foooooo
      graphDbFileName: 'target/var/graphDb'
      embedded:
        enabled: true
      indexes:
        auto:
          dump:
            dir: 'target/var/'
            filename: 'indexes-auto.cypher'
      repositories:
        enabled: true
