spring:
  dao:
    exceptiontranslation:
      enabled: true
  data:
    neo4j:
      URI: bolt://127.0.0.1:7687
      username: neo4j
      password: secret
      encryption:
        level: NONE
      connection:
        pool:
          size: 50
        liveness:
          check:
            timeout: 240
      verify:
        connection: true
      indexes:
        auto:
          dump:
            dir: 'target/var/'
            filename: 'indexes-auto.cypher'
      repositories:
        enabled: true
